# Generated by Django 5.2.5 on 2025-08-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='date',
            new_name='date_added',
        ),
    ]
