# Generated by Django 5.2.5 on 2025-08-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_rename_date_reminder_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
