# Generated by Django 5.2.5 on 2025-08-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_reminder_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
