# Generated by Django 5.2.5 on 2025-08-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_rename_completed_reminder_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='created_by',
            field=models.CharField(default=''),
        ),
    ]
