# Generated by Django 5.2.5 on 2025-08-20 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0006_reminder_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='shared_with',
            field=models.ManyToManyField(related_name='reminders_shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
