# Generated by Django 5.2.5 on 2025-08-20 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_alter_patient_doctor'),
        ('reminders', '0007_reminder_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='shared_with',
        ),
        migrations.AddField(
            model_name='reminder',
            name='shared_with',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reminders_shared', to='authenticate.account'),
        ),
    ]
