# Generated by Django 5.2.5 on 2025-08-20 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0008_remove_reminder_shared_with_reminder_shared_with'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='shared_with',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reminders_shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
