# Generated by Django 5.2.5 on 2025-08-20 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0009_alter_reminder_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='shared_with',
        ),
    ]
