# Generated by Django 5.2.5 on 2025-08-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0013_alter_reminder_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='created_by',
        ),
    ]
