# Generated by Django 5.2.5 on 2025-08-22 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0016_alter_reminder_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
        migrations.AddField(
            model_name='reminder',
            name='user',
            field=models.ManyToManyField(related_name='reminders', to=settings.AUTH_USER_MODEL),
        ),
    ]
