# Generated by Django 5.2.5 on 2025-08-23 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0010_alter_patient_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')])),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('bmi', models.IntegerField()),
                ('allergies', models.CharField(max_length=100)),
                ('medication_history', models.CharField(max_length=300)),
                ('extra_notes', models.TextField()),
                ('current_doctor', models.CharField(max_length=100)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authenticate.patient')),
            ],
        ),
    ]
