# Generated by Django 5.2.5 on 2025-08-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0002_remove_healthrecord_patient_healthrecord_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='record_creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
