# Generated by Django 5.2.5 on 2025-08-24 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0003_healthrecord_record_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='age',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='bmi',
        ),
    ]
