# Generated by Django 5.2.5 on 2025-08-24 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0004_remove_healthrecord_age_remove_healthrecord_bmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='gender',
        ),
    ]
