# Generated by Django 5.2.5 on 2025-08-25 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0013_alter_patient_doctor'),
        ('health_records', '0005_remove_healthrecord_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='current_doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authenticate.doctor'),
        ),
    ]
