# Generated by Django 5.2.5 on 2025-08-25 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0013_alter_patient_doctor'),
        ('health_records', '0006_alter_healthrecord_current_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='current_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.doctor'),
        ),
    ]
