# Generated by Django 5.2.5 on 2025-08-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0007_alter_healthrecord_current_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='record_creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
