# Generated by Django 5.2.5 on 2025-08-25 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0013_alter_patient_doctor'),
        ('health_records', '0008_alter_healthrecord_record_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='current_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticate.doctor'),
        ),
    ]
