# Generated by Django 5.2.5 on 2025-08-19 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_account_enrolled_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='enrolled_patients',
        ),
    ]
