# Generated by Django 5.2.5 on 2025-08-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_remove_account_enrolled_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='doctor',
            field=models.CharField(default='none'),
        ),
    ]
