# Generated by Django 5.2.5 on 2025-08-20 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_remove_account_doctor_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='authenticate.account'),
        ),
    ]
