# Generated by Django 5.2.5 on 2025-08-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_alter_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male'),
        ),
    ]
