# Generated by Django 5.2.5 on 2025-08-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_account_date_of_birth_account_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ManyToManyField(blank=True, null=True, to='authenticate.doctor'),
        ),
    ]
