# Generated by Django 5.2.5 on 2025-08-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0012_remove_patient_doctor_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ManyToManyField(blank=True, null=True, related_name='patients', to='authenticate.doctor'),
        ),
    ]
